### ISSUE TITLE
Issue in line 52 of qualtrics-mailer code

### ISSUE THREAD

**Issue by ErikTDLL** [KaiAnalytics/qualtrics_mailer#1]
Hi Kevin,

as mentioned, I'm facing one issue after completing all steps mentioned in your tutorial. I've copied/pasted the code from GitHub (example_usage.py) and followed all steps even twice but I the same issue continues to arise.

The issue is related to line 52 in the main.py file (see screenshot 1). The error message refers to line 93 in the qualtrics_distribution.py file of the package I've downloaded (see screenshot 2).

Hope you recognize the issue and you know a simple solution for it!

Thanks in advance for your help and let me know in case you need further details!

Kind regards,

Erik.
![screenshot1](https://user-images.githubusercontent.com/41575668/43074030-0f2d3774-8e7c-11e8-9edb-31f01e274aa5.JPG)
![screenshot2](https://user-images.githubusercontent.com/41575668/43074032-0f453644-8e7c-11e8-96ec-8ddfbb56009a.JPG)

**Comment by ErikTDLL** [comment]
Hi Kevin,

I've found the cause of the issue :). The survey I was testing on was not activated yet... Simple but stupid mistake!

**Comment by kaiichang** [comment]
HI Erik,

That's great. Hey don't be so hard on yourself I've made plenty of those while I was creating this!
My apologies for not getting back to you earlier. It's been a busy month for me.
I hope everything else will work for you and that you find this tool useful.
