### ISSUE TITLE
V3 API Compliancy

### ISSUE THREAD

**Issue by jjanicik** [KaiAnalytics/qualtrics_mailer#4]
Kevin,

Are all of the direct API calls made to Qualtrics  version 3?

I am asking because Qualtrics V2 call will be deprecated on 3/31/2020.

Thanks,

Jim

**Comment by kevin-kaianalytics** [comment]
Hi Jim,

Thank you for your question. I can confirm that the package makes direct API calls to Qualtrics Version 3

Sincerely,

Kevin
